#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    
    arr = list(map(int, input().rstrip().split()))
    
    prr = []
    while (n>0 ):
        prr.append(str(arr[n-1]))  
        n=n-1
    
    var = ' '.join(prr)           
    print(var)    
    
    
    
        
